// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebWarriors.Aquanetix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace WebWarriors.Aquanetix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615055810_AddAllBoundedContexts")]
    partial class AddAllBoundedContexts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Dashboard.Domain.Model.Aggregates.QualityAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AnomalyStatus")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("anomaly_status");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DetectedParameters")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("detected_parameters");

                    b.Property<bool>("HasContaminationPeakPrediction")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_contamination_peak_prediction");

                    b.Property<int>("SensorSourceId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_source_id");

                    b.Property<double>("SeverityScore")
                        .HasColumnType("double")
                        .HasColumnName("severity_score");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("quality_analyses", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int")
                        .HasColumnName("current_status");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int")
                        .HasColumnName("device_type");

                    b.Property<DateTimeOffset>("LastTelemetrySync")
                        .HasColumnType("datetime")
                        .HasColumnName("last_telemetry_sync");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Entities.ThresholdConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int")
                        .HasColumnName("alert_level");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double")
                        .HasColumnName("min_value");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("threshold_configurations", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Monitoring.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_name");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<double>("Threshold")
                        .HasColumnType("double")
                        .HasColumnName("threshold");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.ServiceDesign.Domain.Model.Aggregates.WaterBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CertificationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("certification_code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DeliveryTimestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("delivery_timestamp");

                    b.Property<int>("DestinationSectorId")
                        .HasColumnType("int")
                        .HasColumnName("destination_sector_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("double")
                        .HasColumnName("volume_liters");

                    b.HasKey("Id");

                    b.ToTable("water_batches", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Entities.ThresholdConfiguration", b =>
                {
                    b.HasOne("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", null)
                        .WithMany("Thresholds")
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", b =>
                {
                    b.Navigation("Thresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
