// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebWarriors.Aquanetix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace WebWarriors.Aquanetix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611034729_TemporalFix")]
    partial class TemporalFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int")
                        .HasColumnName("current_status");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int")
                        .HasColumnName("device_type");

                    b.Property<DateTimeOffset>("LastTelemetrySync")
                        .HasColumnType("datetime")
                        .HasColumnName("last_telemetry_sync");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Entities.ThresholdConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int")
                        .HasColumnName("alert_level");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double")
                        .HasColumnName("min_value");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("threshold_configurations", (string)null);
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Entities.ThresholdConfiguration", b =>
                {
                    b.HasOne("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", null)
                        .WithMany("Thresholds")
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("WebWarriors.Aquanetix.Platform.Devices.Domain.Model.Aggregates.Device", b =>
                {
                    b.Navigation("Thresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
